### ISSUE TITLE
Dexterity configuration

### ISSUE THREAD

**Issue by lucianux** [collective/stxnext.staticdeployment#12]
StxNext.
Hi, my name is Jesus. I am from Argentina. I'm using your software in a institutional website in my University.
I wonder how I can configure my custom types made by Dexterity. Your software support Dexterity, that is great. So I don't know how to use the file called "staticdeployment.ini" in etc/. I want to make clear that I made my custom types programatically by an addon (not through-the-web).
Please, give a hand.
In advence thank you.
Cheers.
Jesús.

**Comment by radekj** [comment]
The Dexterity support has been added in version 1.1.

You can find the detailed description of the staticdeployment.ini file's parameters here: https://github.com/collective/stxnext.staticdeployment#staticdeploymentini-paramaters

For example, if you want to create a static version of your site that would include your custom content types, you need to:
1. create a directory in location: ${buildout:directory}/etc
2. place there a copy of the staticdeployment.ini file to be customized
3. list your content types' portal_type parameter in the 'page-types' section of the staticdeployment.ini (example here: https://github.com/collective/stxnext.staticdeployment/blob/master/src/stxnext/staticdeployment/etc/staticdeployment.ini#L11)

Let me know if this hint was sufficent to achieve what you need.
