### ISSUE TITLE
from zope.component.interfaces import IResource

### ISSUE THREAD

**Issue by Siggg** [collective/stxnext.staticdeployment#15]
I could not install stxnet.staticdeployment v.1.1 under Plone 4.3.2
I got this error message when starting my plone instance :

ZopeXMLConfigurationError: File ".../.shared/eggs/stxnext.staticdeployment-1.1-py2.7.egg/stxnext/staticdeployment/app/configure.zcml", line 5.4-8.7
    ImportError: cannot import name IResource

[Edit : bad copy and paste initially.]

**Comment by radekj** [comment]
Fixes for compatibility with Plone 4.3 has been pushed into master branch
