### ISSUE TITLE
Dexterity Content types

### ISSUE THREAD

**Issue by libargutxi** [collective/stxnext.staticdeployment#2]
Hi!

I'm trying to use your product with dexterity content types. I added in staticdeployment.ini a dexterity content type but I have problems with ímage fields ...

Can I use your product with dexterity content types?

Moreover, adding a Image in a ATDocument text field (TinyMCE) I have problems with plone.outputfilters because @@images/image/mini its rendered for instance like /@@images/7a43ecab-7b02-4d35-9573-ccef63ba4a17.jpeg an your product doesn't create that image.

My Plone version is 4.2.4

**Comment by radekj** [comment]
This add-on is not compatibile with Dexterity Content types yet.

**Comment by libargutxi** [comment]
ok, maybe maybe we can add that funtionality to the product ...

What about the plone.outputfilters problem? You know about this problem or I'm doing something wrong?

**Comment by radekj** [comment]
+1 for dexterity support

Regarding your images links issue - this is quite complex topic an perhaps not all the use-cases are covered. Anyway, please try the newest release containing Nathan's changes (1.0.4), maybe after his changes your images will work properely

**Comment by erral** [comment]
Fixed.

**Comment by radekj** [comment]
Released in v1.1
