### ISSUE TITLE
diazo themes not working

### ISSUE THREAD

**Issue by vangheem** [collective/stxnext.staticdeployment#4]
Even though the documentation hints that it should work with diazo, it does not work.

I put a debug statement in app/diazo.py and stepped through the diazo code and I couldn't make sense of why diazo was refusing to execute rules just with this.

**Comment by vangheem** [comment]
I actually just fixed this in the pull request that includes other fixes.

**Comment by radekj** [comment]
Yes, I confirm your commit fixes the problem with diazo theme enabled. I merged in your pull request and released a new version (1.0.3).

Thanks!
