### ISSUE TITLE
move to the collective?

### ISSUE THREAD

**Issue by vangheem** [collective/stxnext.staticdeployment#8]
Would you be okay with me moving the repo to the collective so I don't have to do anymore pull requests?

**Comment by radekj** [comment]
Yes, I agree. I'll transfer this repo to collective, but the transfer form requires me to enter the username of the  destination's repository (collective) usrer with admin rights (https://help.github.com/articles/how-to-transfer-a-repository). Could you help me with finding out whose username should I enter?

**Comment by vangheem** [comment]
I believe the way most people do it is to just fork to the collective and then delete the original.

**Comment by radekj** [comment]
Update on this issue: I asked one of the collective's admins (@miohtama) and it seems that the appropriate way of transferring the repositories between organizations is not speciffied yet, the discussion on this topic is here: https://github.com/collective/collective.github.com/issues/676

**Comment by miohtama** [comment]
Hi @Radekj,

Is it possible to 

1) create a new group within stxnext organization
2) put me in this group
3) add this group ownership in staticdeployment repo

I think this should do the trick.

**Comment by radekj** [comment]
Hi @miohtama,

I created a new team within stxnext organization (opensource) and assigned administrative privilages for the stxnext.staticdeployment repository for this group. Let me know if it's sufficient.

**Comment by miohtama** [comment]
And behold... it is done. 

I'll update collective.github.com documentation how the process is done.

**Comment by radekj** [comment]
Thanks Mikko!
