### ISSUE TITLE
Filter based on portal_type instead of meta_type

### ISSUE THREAD

**Issue by erral** [collective/stxnext.staticdeployment#9]
I'm working on a version that works with Dexterity, but for some reason all Dexterity content-types have 'Dexterity Container' or 'Dexterity Item' no matter their portal type.

With this small change we can filter also by Dexterity portal_types.

What do you think about it?

**Comment by radekj** [comment]
Looks good to me.

Perhaps also the default config file (https://github.com/collective/stxnext.staticdeployment/blob/master/src/stxnext/staticdeployment/etc/staticdeployment.ini) should be changed (ATEvent -> Event and so on).

**Comment by erral** [comment]
Yes, the default config file also should be changed.

I have these canges and some more in my fork, i'll be merging them in a
couple of days.

2013/4/18 Radek Jankiewicz notifications@github.com

> Looks good to me.
> 
> Perhaps also the default config file (
> https://github.com/collective/stxnext.staticdeployment/blob/master/src/stxnext/staticdeployment/etc/staticdeployment.ini)
> should be changed (ATEvent -> Event and so on).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/collective/stxnext.staticdeployment/issues/9#issuecomment-16566824
> .

## 

Mikel Larreategi
mlarreategi@codesyntax.com

CodeSyntax
Azitaingo Industrialdea 3 K
E-20600 Eibar
Tel: (+34) 943 82 17 80

**Comment by radekj** [comment]
Released in v1.1
